// tslint:disable
/**
 * Glodon PDC Catalog Service
 * # 概览  `PDC` = Project Data Center  ```yaml hello: world ```  # 概念及术语  ### 概念   ### 术语  #### Domain
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./configuration";
