export enum EnumDomainRoles {
  'ROLE_DOMAIN_OWNER' = 'ROLE_DOMAIN_OWNER',
  'ROLE_DOMAIN_ADMIN' = 'ROLE_DOMAIN_ADMIN',
  'ROLE_DOMAIN_DEV' = 'ROLE_DOMAIN_DEV',
  'ROLE_DOMAIN_OPER' = 'ROLE_DOMAIN_OPER',
  'ROLE_DOMAIN_USER' = 'ROLE_DOMAIN_USER'
}

export enum EnumDomainRolesNames {
  'ROLE_DOMAIN_OWNER' = '域所有者',
  'ROLE_DOMAIN_ADMIN' = '域管理员',
  'ROLE_DOMAIN_DEV' = '开发者',
  'ROLE_DOMAIN_OPER' = '运营者',
  'ROLE_DOMAIN_USER' = '访客'
}
